name: my_GHActions

on:
 push:
   branches:
    - master

jobs:
 my-testing:
  runs-on: ubuntu-latest

  steps:
  - name: Print Hello Massage
    run: echo "Hello World from Testing job"

 my-deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Print Hello Massage
      run: echo "Hello World from Deploy job"
     
 
  

  
